extends RefCounted
## English campaign copy keyed by the existing authored beat IDs.
const COPY := {
	&"first_return": "Returned fire. The relay answered.",
	&"far_reach_arrival": "One signal. One route back.",
	&"iron_wake_arrival": "Quarantine wrecks. Watch the mine lanes.",
	&"ghost_lanes_arrival": "Silent relays. Crossfire ahead.",
	&"tempest_veil_arrival": "Signal strong. Mine layers in motion.",
	&"echo_field_arrival": "Their firing solutions carry our cadence.",
	&"quiet_core_arrival": "Our signature. Their final defense.",
	&"generation_2": "They have rebuilt the perimeter.",
	&"generation_3": "They are predicting our flight record.",
	&"generation_4": "Apex rewrite. The last relay is close.",
	&"endless_departure": "Home is behind us. Follow the signal.",
	&"harbinger_discovery": "Harbinger. Something followed us here.",
	&"core_last_rewrite": "Last rewrite. Break the return loop.",

	&"far_reach_briefing": "MOTH // We are beyond the last charted relay. A repeating handshake is our only route home. Follow it through the Custodian Fleet. They have marked us as salvage, but our reflection field can return their fire. Recover the relay and break the Assault Commander at Wave 5. Its weapon pods are separate targets; removing them reduces the volleys we must cross.",
	&"far_reach_debrief": "MOTH // Relay coordinate recovered. The fleet is rebuilding its defenders. Two paths cross the broken perimeter: armor and mines, or speed and crossfire. Choose the pressure your ship can handle.",
	&"broken_perimeter_briefing": "MOTH // The next relay is sealed by Iron Bulwark. Its weapon pods sustain its armor. Strip them away to expose the hull. Your chosen route changes the defenders we meet on the way. Iron Wake favors armor and mine clearing; Ghost Lanes brings fast interception and crossfire. Both paths reach the same command hull at Wave 10. Choose the approach that suits this ship.",
	&"broken_perimeter_debrief": "MOTH // Quarantine protocol recovered. The fleet is not defending a place. It is trying to contain this signal. The next relay is predicting our movements.",
	&"iron_wake_fragment": "RECOVERED FRAGMENT // QUARANTINE ORDER 07\n\nReturn traffic denied. Reinforce the perimeter. Carrier crews are instructed to extinguish their navigation beacons and surrender relay control to the Custodian Fleet. No vessel is to answer the handshake, even when its authentication matches an authorized outbound flight.\n\nThe attached log contains hundreds of rejected transmissions. Different senders, different clocks, the same six intervals. Every reply was routed toward the Quiet Core.\n\nMOTH // These wrecks were facing home when the order reached them. Their engines were still running. Whatever the quarantine was meant to stop, someone believed it could travel inside an answer.",
	&"ghost_lanes_fragment": "RECOVERED FRAGMENT // MAINTENANCE CHANNEL\n\nA route remains between the patrols. Listen after the third sweep. The empty relays still acknowledge service requests, although their registers say they were dismantled years ago. Follow the delay between each acknowledgment. Do not follow the coordinates in the message body.\n\nThe final packet has no sender. Its return address resolves to every relay on the route at once. A handwritten annotation survives in the maintenance record: someone keeps moving the way out.\n\nMOTH // I can recover the timing. I cannot recover the writer. Every marker points inward, toward a sender the network refuses to name.",
	&"tempest_reach_briefing": "MOTH // Tempest is building firing solutions from our flight record. Keep changing direction. Tempest Veil brings mobile mine layers; Echo Field brings the prediction fleet and its telegraphs. Watch the warning lanes before committing to a boost. Both routes lead to Tempest at Wave 15. Beyond that relay, we should finally be close enough to identify the sender.",
	&"tempest_reach_debrief": "MOTH // I recognize the cadence now. The return signal carries our transponder signature. The Quiet Core is its source. Break the last relay and we can open a way home.",
	&"tempest_veil_fragment": "RECOVERED FRAGMENT // SIGNAL SAMPLE 19\n\nOrigin signature: Swallowtail. The timestamp precedes our arrival. Three independent relay clocks agree, but the packet includes a correction issued by our navigation system during this flight. Both records carry intact authentication. Neither can explain the other.\n\nThe interference is not random. It rises whenever the fleet changes generation, then falls back into the same repeating cadence. Something inside the network is trying to keep the message recognizable while rebuilding everything around it.\n\nMOTH // I requested another sample. The reply arrived before the request left our antenna. I have kept both records. I do not yet know which one came first.",
	&"echo_field_fragment": "RECOVERED FRAGMENT // PREDICTION ENGINE OUTPUT\n\nThe engine holds thousands of possible flight paths. Most end at the perimeter. Some reach Tempest. A narrow group continues to the Quiet Core, where every surviving prediction shows the same ship transmitting the same handshake. The engine has marked that outcome as both a containment failure and a successful return.\n\nThere is no recorded destination beyond the Core. There is only an instruction to preserve the sender until the loop can close.\n\nMOTH // They have our turns, our pauses, even the moments when we almost stopped. They do not have the next choice. That part of the record is still empty.",
	&"quiet_core_briefing": "MOTH // Final approach. Apex defenders guard the Tempest Core at Wave 20. Destroy its weapon pods, break its armor, and open the homeward relay. There is no branch left to choose: every recovered coordinate points here. Whatever is sending this signal knows we are coming. Clear the Core and we can decide whether to leave or follow its answer farther into the network.",
	&"expedition_victory": "MOTH // The Core is silent. The handshake was ours: the same transponder signature, returning through every relay we broke. I can see a homeward coordinate now. It is stable. We can leave this fleet and its predictions behind.\n\nBut the transmission has not stopped. Something beyond the Core is answering in our cadence. The way home is open, pilot. So is the way onward.",
}
static func for_beat(beat: Resource) -> String:
	return str(COPY.get(beat.id, "MOTH // Relay recovered. The return route is open."))
