extends RefCounted
class_name Native3DPhysicsLayers
## Named layer bits and interaction masks for native 3D overlap gameplay.

const PLAYER_CRAFT := 1 << 0
const ENEMY_CRAFT := 1 << 1
const PLAYER_PROJECTILE := 1 << 2
const ENEMY_PROJECTILE := 1 << 3
const PICKUP := 1 << 4
const HOSTILE_ORDNANCE := 1 << 5

const PLAYER_CRAFT_MASK := ENEMY_CRAFT | ENEMY_PROJECTILE | PICKUP | HOSTILE_ORDNANCE
const ENEMY_CRAFT_MASK := PLAYER_CRAFT | PLAYER_PROJECTILE
const PLAYER_PROJECTILE_MASK := ENEMY_CRAFT | PICKUP | HOSTILE_ORDNANCE
const ENEMY_PROJECTILE_MASK := PLAYER_CRAFT
const PICKUP_MASK := PLAYER_CRAFT | PLAYER_PROJECTILE
const HOSTILE_ORDNANCE_MASK := PLAYER_CRAFT | PLAYER_PROJECTILE
